---
- hosts: webapi
  gather_facts: no
  environment:
      console_ip: "192.168.56.102"
      console_user: "admin"
      console_password: "S0meP@ssword"
  vars:
    add_set: True
    del_data: True
    del_set: True

  tasks:
    - name: add reference set
      qradar_data:
        ref_name: 'testset'
        timetolive: "1 month"
        ref_col_type: 'SET'
        ref_data_type: 'IP'
        ref_data: 
           - '172.0.0.1'
           - '132.0.0.1'
      when: add_set
      register: result
    - name: debug
      debug:
        var: result
        verbosity: 0

    - name: remove reference set data
      qradar_data:
        ref_col_type: 'SET'
        ref_name: 'testset'
        state: 'absent'
        ref_data: 
           value: '132.0.0.1'
      when: del_data
      register: result
    - name: debug
      debug:
        var: result
        verbosity: 0

    - name: remove reference set
      qradar_data:
        ref_col_type: 'SET'
        ref_name: 'testset'
        state: 'absent'
      when: del_set
      register: result
    - name: debug
      debug:
        var: result
        verbosity: 0

